// ── PORTAFOLIO ESTRATÉGICO (Senior CSM View / Aceleración Portfolio A) ──────────
// Extracted verbatim from index.html (source lines 6978-7300).
// Verified by brace-matching against the ground-truth file: renderPortfolioA opens
// at 6978 `function renderPortfolioA() {`, its matching closing `}` is line 7300
// (immediately followed by `</script>` at 7303 — this is the LAST function in the
// monolith's main script block) — confirmed complete, not truncated.
//
// IMPORTANT CORRECTION vs. this task's brief: the brief suggested importing
// PORTFOLIO_GAP/GRUPO_ESTRATEGICO from '../domain/tiers.js'. Verified by reading the
// full 6978-7300 body: renderPortfolioA does NOT reference either constant anywhere.
// A whole-file grep confirms PORTFOLIO_GAP/GRUPO_ESTRATEGICO (defined index.html:6936
// and 6960, immediately BEFORE this function) are only consumed by renderOverview
// (index.html:3021, src/ui/overview.js) and renderPortfolioReview (index.html:
// 5912-5994, "3 Rounds" page, src/ui/portfolio-review.js). renderPortfolioA instead
// defines its own, entirely separate CLASS_A / CLASS_B / GROUPS constants inline.
// domain/tiers.js's header comment claiming it backs "Portafolio Estratégico
// (renderPortfolioA)" is therefore misleading — no import from tiers.js is added
// here, to avoid an unused/incorrect import.
//
// `saveSD` is a function nested INSIDE renderPortfolioA's closure (not module-level)
// — it closes over nothing external, but is only reachable from inline onclick/
// onblur/onchange HTML strings generated by this same function (e.g.
// onclick="saveSD_('<id>','renewalConf','<n>')"). The source solves this by
// re-assigning `window.saveSD_ = saveSD;` as the LAST statement inside
// renderPortfolioA, every time the page renders — preserved exactly as-is (not
// hoisted to module scope, not renamed) since that's the verbatim source behavior.
//
// DEAD REFERENCE preserved verbatim per extraction rules: `saveSD` calls
// `setTimeout(updatePipelineTotal, 100)` (source line 7028). A whole-file grep of
// index.html for `function updatePipelineTotal` and for any other occurrence of the
// identifier `updatePipelineTotal` turns up ONLY this one call site — the function
// is never defined anywhere in the 7489-line source. This is a genuine bug in the
// original dashboard (the setTimeout callback will throw a ReferenceError,
// asynchronously, whenever any editable Class-A strategic field is blurred/changed).
// Kept exactly as-is, uncommented-out and unresolved, per the "preserve dead/broken
// code verbatim" rule.
//
// ASSUMED CROSS-FILE IMPORTS (sibling files did not exist yet at extraction time —
// verify these during integration):
//   - getClients   from '../services/clients-repo.js'  (confirmed export)
//   - PORT         from '../services/clients-repo.js'  (confirmed export)
//   - calcHS       from '../domain/health-score.js'    (confirmed export)
//   - getMRR       from '../domain/renewal-revenue.js' (confirmed export)
import { getClients } from '../services/clients-repo.js';
import { PORT } from '../services/clients-repo.js';
import { calcHS } from '../domain/health-score.js';
import { getMRR } from '../domain/renewal-revenue.js';

function renderPortfolioA() {
  const pg = document.getElementById('page-portfolio-a');
  if (!pg) return;

  // ─── CLASS A DEFINITION ────────────────────────────────────────────────────
  // Criterios: Enterprise porte + grupos estratégicos + potencial de expansión
  const CLASS_A = [
    // BELCORP GROUP — un ejecutivo regional mueve 4 países
    { id:'belcorp-chile', group:'💄 Belcorp LATAM', groupColor:'#e879f9', reason:'Enterprise · Belleza · multinacional · sponsor regional disponible' },
    { id:'belcorp-col',   group:'💄 Belcorp LATAM', groupColor:'#e879f9', reason:'Enterprise · Belleza · expansión de canales CO' },
    { id:'belcorp-mex',   group:'💄 Belcorp LATAM', groupColor:'#e879f9', reason:'Enterprise · Belleza · mercado MX de alto volumen' },
    { id:'belcorp-peru',  group:'💄 Belcorp LATAM', groupColor:'#e879f9', reason:'Enterprise · Belleza · expansión PE' },
    { id:'transbel',      group:'💄 Belcorp LATAM', groupColor:'#e879f9', reason:'Enterprise · Belcorp MX · cuenta puente para LATAM' },
    // FORUS GROUP — migración activa = oportunidad de expansión post-migración
    { id:'forus-sa',      group:'👟 Forus Group',   groupColor:'#34d399', reason:'Enterprise · Calzado · migración activa · Chile flagship' },
    { id:'forus-colombia',group:'👟 Forus Group',   groupColor:'#34d399', reason:'Enterprise · Calzado · migración bloqueada Dafiti — acción urgente' },
    { id:'forus-peru',    group:'👟 Forus Group',   groupColor:'#34d399', reason:'Enterprise · Calzado · migración + expansión PE' },
    // EMMA SLEEP — marca global con modelo replicable
    { id:'emma-sleep',    group:'🛏️ Emma Sleep',    groupColor:'#60a5fa', reason:'Mid Market → Enterprise · Hogar · modelo CL replicable en CO' },
    { id:'emma-sleep-co', group:'🛏️ Emma Sleep',    groupColor:'#60a5fa', reason:'Growth · Hogar · replicar éxito CL en CO' },
    // TRAMONTINA — benchmark MX → CL
    { id:'tramontina-mx', group:'🍳 Tramontina',    groupColor:'#fb923c', reason:'Enterprise · Hogar · 5 canales MX = caso de éxito para CL' },
    { id:'tramontina-cl', group:'🍳 Tramontina',    groupColor:'#fb923c', reason:'Enterprise · Hogar · solo 2 canales activos → oportunidad masiva' },
    // MARCAS PREMIUM individuales
    { id:'lacoste',       group:null,               groupColor:null,       reason:'Enterprise · Moda Premium · marca aspiracional · alto potencial NPS' },
    { id:'lacoste-gen',   group:null,               groupColor:null,       reason:'Enterprise · Moda Premium · expansión de canales CL' },
    { id:'whirlpool',     group:null,               groupColor:null,       reason:'Enterprise · Electrodomésticos · marca global · QBR ejecutivo pendiente' },
    { id:'kayser',        group:null,               groupColor:null,       reason:'Enterprise · Moda · alto GMV CL · adopción Repricing pendiente' },
    { id:'colombiana',    group:null,               groupColor:null,       reason:'Enterprise · Retail CO · expansión de canales Colombia' },
  ];

  const CLASS_B = ['fashions-park','coboe-botiga','coboe-farmashop','divino','dtodoymas','pointbreak','lounge','maisa','gino','loi-chile','maui','pillin'];
  const CLASS_A_IDS = CLASS_A.map(x=>x.id);

  // ─── STRATEGIC GROUPS ──────────────────────────────────────────────────────
  const GROUPS = {
    '💄 Belcorp LATAM': { color:'#e879f9', insight:'Una reunión con el VP Regional = 4 países alineados. ARR consolidado supera cualquier cuenta individual. La jugada: proponer un "Belcorp LATAM Partnership Review" semestral.', urgency:'alta' },
    '👟 Forus Group':   { color:'#34d399', insight:'La migración de FORUS SA es el caso de éxito que vende Forus Colombia y Peru. Cada milestone completado = argumento para desbloquear Dafiti.', urgency:'alta' },
    '🛏️ Emma Sleep':    { color:'#60a5fa', insight:'CL tiene 6+ canales activos. CO tiene 2. Presentar el modelo CL como roadmap para CO = expansión inmediata sin vender nada nuevo.', urgency:'media' },
    '🍳 Tramontina':    { color:'#fb923c', insight:'MX tiene 5 canales y es caso de éxito. CL solo tiene 2. Una sola reunión con el ejecutivo de CL presentando los resultados de MX = apertura de 3 canales nuevos.', urgency:'media' },
  };

  // ─── EDITABLE STRATEGIC DATA (localStorage) ────────────────────────────────
  function getSD(id) {
    try { return JSON.parse(localStorage.getItem('cs-strat-'+id)||'{}'); } catch(e){ return {}; }
  }
  function saveSD(id, key, value) {
    const d = getSD(id); d[key] = value;
    localStorage.setItem('cs-strat-'+id, JSON.stringify(d));
    // Update expansion pipeline total
    setTimeout(updatePipelineTotal, 100);
  }

  // ─── GET CURRENT CLIENT DATA ────────────────────────────────────────────────
  function getClientData(id) {
    return getClients().find(c=>c.id===id) || {};
  }
  function getPortData(id) {
    return PORT.find(p=>p.id===id) || {};
  }

  // ─── FINANCIAL ESTIMATES ────────────────────────────────────────────────────
  const allClients = getClients() || [];
  const allHS = allClients.map(c=>calcHS(c));

  const totalARR = allClients.reduce((s,c)=>s+(getMRR(c.id)||0)*12, 0);
  const atRiskClients = allClients.filter((_,i)=>['red','orange'].includes(allHS[i]?.cl));
  const arrAtRisk = atRiskClients.reduce((s,c)=>s+(getMRR(c.id)||0)*12, 0);

  // Expansion pipeline from user-entered strategic data
  let pipelineTotal = CLASS_A.reduce((s,a)=>s+(parseInt(getSD(a.id).expansionArr||0)*12),0);

  // NRR projection: (ARR + pipeline - risk) / ARR
  const nrrProjection = totalARR > 0 ? Math.round(((totalARR + pipelineTotal - arrAtRisk)/totalARR)*100) : null;
  const nrrColor = nrrProjection==null?'var(--text3)':nrrProjection>=110?'var(--green)':nrrProjection>=100?'var(--yellow)':'var(--red)';
  const nrrLabel = nrrProjection==null?'—':nrrProjection+'%';

  const fmtArr = v => v>=1000?'$'+(v/1000).toFixed(0)+'K':'$'+v;

  // ─── BUILD STRATEGIC GROUP CARDS ───────────────────────────────────────────
  const groupNames = [...new Set(CLASS_A.filter(x=>x.group).map(x=>x.group))];
  const groupCards = groupNames.map(gname => {
    const g = GROUPS[gname];
    const members = CLASS_A.filter(x=>x.group===gname);
    const memberNames = members.map(m=>getPortData(m.id).name||m.id).join(' · ');
    const urgBg = g.urgency==='alta'?'rgba(231,76,60,.08)':'rgba(243,156,18,.06)';
    const urgBorder = g.urgency==='alta'?'rgba(231,76,60,.25)':'rgba(243,156,18,.2)';
    return `<div style="background:${urgBg};border:1px solid ${urgBorder};border-left:4px solid ${g.color};border-radius:12px;padding:16px 18px;flex:1;min-width:260px">
      <div style="display:flex;align-items:center;gap:8px;margin-bottom:6px">
        <span style="font-size:16px">${gname.split(' ')[0]}</span>
        <span style="font-weight:800;font-size:13px;color:${g.color}">${gname.substring(2)}</span>
        <span style="margin-left:auto;font-size:10px;padding:2px 8px;border-radius:8px;font-weight:700;
          background:${g.urgency==='alta'?'rgba(231,76,60,.15)':'rgba(243,156,18,.12)'};
          color:${g.urgency==='alta'?'var(--red)':'var(--yellow)'}">
          ${g.urgency==='alta'?'🔴 PRIORIDAD ALTA':'🟡 PRIORIDAD MEDIA'}
        </span>
      </div>
      <div style="font-size:11px;font-weight:600;color:var(--text3);margin-bottom:8px">${members.length} cuentas · ${memberNames}</div>
      <div style="font-size:12px;color:var(--text2);line-height:1.6;border-top:1px solid ${urgBorder};padding-top:8px">
        💡 <em>${g.insight}</em>
      </div>
    </div>`;
  }).join('');

  // ─── BUILD CLASS A ACCOUNT CARDS ───────────────────────────────────────────
  const classACards = CLASS_A.map(entry => {
    const port  = getPortData(entry.id);
    const cdata = getClientData(entry.id);
    const hs    = calcHS(cdata);
    const sd    = getSD(entry.id);
    const mrr   = getMRR(entry.id);
    const arr   = mrr ? mrr*12 : null;

    const hsCol = hs.cl==='green'?'var(--green)':hs.cl==='yellow'?'var(--yellow)':hs.cl==='orange'?'var(--orange)':'var(--red)';
    const groupBadge = entry.group
      ? `<span style="background:${entry.groupColor}20;color:${entry.groupColor};font-size:10px;padding:2px 8px;border-radius:8px;font-weight:700">${entry.group}</span>`
      : '';

    // Renewal confidence stars
    const conf = parseInt(sd.renewalConf||0);
    const stars = [1,2,3,4,5].map(n=>`<span onclick="saveSD_('${entry.id}','renewalConf','${n}')" style="cursor:pointer;font-size:14px;color:${n<=conf?'var(--yellow)':'var(--border)'}">★</span>`).join('');

    const inputStyle = `width:100%;background:transparent;border:none;border-bottom:1px dashed var(--border);color:var(--text);font-size:12px;padding:3px 0;outline:none;font-family:inherit`;
    const labelStyle = `font-size:10px;font-weight:700;color:var(--text3);text-transform:uppercase;letter-spacing:.5px;display:block;margin-bottom:3px`;

    return `<div id="strat-card-${entry.id}" style="background:var(--surface);border:1px solid var(--border);border-top:3px solid ${entry.group?entry.groupColor:'var(--accent)'};border-radius:14px;padding:18px;display:flex;flex-direction:column;gap:12px">
      <!-- Header -->
      <div style="display:flex;align-items:flex-start;gap:10px">
        <div style="flex:1;min-width:0">
          <div style="font-weight:800;font-size:13px;color:var(--text);margin-bottom:3px">${port.name||entry.id}</div>
          <div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap">
            ${groupBadge}
            <span style="font-size:10px;color:var(--text3)">${port.country||''} · ${port.segmento||''}</span>
            ${hs.score!=null?`<span style="background:${hsCol}20;color:${hsCol};font-size:11px;font-weight:700;padding:2px 7px;border-radius:8px">⬛ ${hs.score}</span>`:''}
            ${arr?`<span style="font-size:10px;color:var(--text3)">ARR ${fmtArr(arr)}</span>`:''}
          </div>
          <div style="font-size:10px;color:var(--text3);margin-top:3px;line-height:1.4;font-style:italic">${entry.reason}</div>
        </div>
        <button onclick="currentClient='${entry.id}';nav('ficha',document.getElementById('nav-ficha'))"
          style="flex-shrink:0;background:var(--surface2);border:1px solid var(--border);color:var(--text2);padding:5px 10px;border-radius:8px;cursor:pointer;font-size:11px">
          📋 Ficha
        </button>
      </div>

      <!-- Strategic fields grid -->
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px">
        <div>
          <label style="${labelStyle}">🤝 Exec Sponsor</label>
          <input style="${inputStyle}" value="${sd.execSponsor||''}" placeholder="Nombre · Cargo"
            onblur="saveSD_('${entry.id}','execSponsor',this.value)">
        </div>
        <div>
          <label style="${labelStyle}">📅 Renovación</label>
          <div style="display:flex;align-items:center;gap:6px">
            <input type="date" style="${inputStyle};flex:1" value="${sd.renewalDate||''}"
              onchange="saveSD_('${entry.id}','renewalDate',this.value)">
            <div style="white-space:nowrap">${stars}</div>
          </div>
        </div>
        <div style="grid-column:1/-1">
          <label style="${labelStyle}">🎯 Business Outcome — ¿Qué quiere lograr el cliente?</label>
          <input style="${inputStyle}" value="${sd.businessOutcome||''}" placeholder="ej. Aumentar GMV 30% en Falabella y Paris en Q3"
            onblur="saveSD_('${entry.id}','businessOutcome',this.value)">
        </div>
        <div style="grid-column:1/-1">
          <label style="${labelStyle}">⚡ Mi Próxima Jugada Estratégica</label>
          <input style="${inputStyle}" value="${sd.nextPlay||''}" placeholder="ej. QBR ejecutivo Q3 — presentar ROI + proponer Repricing automático"
            onblur="saveSD_('${entry.id}','nextPlay',this.value)">
        </div>
        <div>
          <label style="${labelStyle}">💰 Oportunidad de Expansión</label>
          <input style="${inputStyle}" value="${sd.expansionType||''}" placeholder="ej. Repricing + TikTok Shop"
            onblur="saveSD_('${entry.id}','expansionType',this.value)">
        </div>
        <div>
          <label style="${labelStyle}">💵 MRR adicional estimado (USD)</label>
          <input type="number" style="${inputStyle}" value="${sd.expansionArr||''}" placeholder="ej. 500"
            onblur="saveSD_('${entry.id}','expansionArr',this.value)">
        </div>
      </div>
    </div>`;
  }).join('');

  // ─── EXPANSION PIPELINE TABLE ───────────────────────────────────────────────
  const pipelineRows = CLASS_A.filter(a=>getSD(a.id).expansionArr>0).map(a => {
    const sd = getSD(a.id);
    const port = getPortData(a.id);
    const arr = parseInt(sd.expansionArr||0)*12;
    return `<tr>
      <td><strong>${port.name||a.id}</strong></td>
      <td>${sd.expansionType||'—'}</td>
      <td style="color:var(--green);font-weight:700">${fmtArr(arr)}/año</td>
      <td style="font-size:11px;color:var(--text2)">${sd.nextPlay||'—'}</td>
    </tr>`;
  }).join('');

  // ─── AUTO-PRIORITIES ────────────────────────────────────────────────────────
  const priorities = [];

  // P1: blocked migrations
  const blockedMig = CLASS_A.filter(a=>getClientData(a.id)?.centry && a.id==='forus-colombia');
  if (blockedMig.length) priorities.push({ icon:'🚫', title:'Desbloquear migración FORUS COLOMBIA', detail:'Bloqueada por Dafiti — escalar con PM para resolución esta semana. Cada semana sin migrar es churn risk real.', urgency:'🔴' });

  // P2: red health accounts in Class A
  const redA = CLASS_A.filter(a=>{const h=calcHS(getClientData(a.id));return h.cl==='red'||h.cl==='orange';});
  if (redA.length) priorities.push({ icon:'❤️‍🔥', title:`${redA.length} Cuenta${redA.length>1?'s':''} Clase A con Health crítico`, detail:redA.slice(0,2).map(a=>getPortData(a.id).name||a.id).join(' · ') + ' — requieren contacto ejecutivo en <48hs.', urgency:'🔴' });

  // P3: Class A with no exec sponsor or next play
  const missingStrat = CLASS_A.filter(a=>!getSD(a.id).execSponsor||!getSD(a.id).nextPlay);
  if (missingStrat.length) priorities.push({ icon:'📋', title:`Completar tracker estratégico para ${Math.min(missingStrat.length,3)} cuentas Clase A`, detail:'Sponsor y próxima jugada vacíos = no podés gestionar lo que no medís. 10 minutos por cuenta.', urgency:'🟡' });

  // P4: Group multiplier opportunity
  priorities.push({ icon:'💄', title:'Corporate Review — Belcorp LATAM', detail:'Una reunión con el ejecutivo regional de Belcorp puede alinear Chile + Colombia + Mexico + Peru simultáneamente. ARR combinado es el más alto de la cartera.', urgency:'🟡' });

  const priorityItems = priorities.slice(0,3).map((p,i)=>`
    <div style="background:var(--surface2);border-radius:10px;padding:14px 16px;display:flex;gap:12px;align-items:flex-start">
      <div style="font-size:20px;flex-shrink:0">${p.icon}</div>
      <div style="flex:1">
        <div style="font-size:13px;font-weight:700;color:var(--text);margin-bottom:3px">${p.urgency} P${i+1} — ${p.title}</div>
        <div style="font-size:12px;color:var(--text2);line-height:1.5">${p.detail}</div>
      </div>
    </div>`).join('');

  // ─── UPDATE BADGE ────────────────────────────────────────────────────────────
  const nb = document.getElementById('nb-portfolio-a');
  if (nb) nb.textContent = CLASS_A.length;

  // ─── RENDER ──────────────────────────────────────────────────────────────────
  pg.innerHTML = `<div style="padding:0 0 60px">

    <!-- HEADER -->
    <div style="margin-bottom:20px;padding-bottom:16px;border-bottom:1px solid var(--border)">
      <div style="font-size:20px;font-weight:900;color:var(--text);margin-bottom:4px">💎 Portafolio Estratégico — Senior CSM View</div>
      <div style="font-size:12px;color:var(--text3);line-height:1.6">
        Un CSM Senior no administra tickets — <strong style="color:var(--accent)">protege y expande revenue</strong>.
        Esta vista te ayuda a gestionar el 20% de cuentas que generan el 80% del valor.
      </div>
    </div>

    <!-- NRR STRIP -->
    <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:24px">
      <div style="background:rgba(99,102,241,.08);border:1px solid rgba(99,102,241,.25);border-radius:12px;padding:16px">
        <div style="font-size:10px;font-weight:700;color:var(--text3);text-transform:uppercase;letter-spacing:.6px;margin-bottom:6px">NRR Proyectado</div>
        <div style="font-size:28px;font-weight:900;color:${nrrColor};margin-bottom:2px">${nrrLabel}</div>
        <div style="font-size:10px;color:var(--text3)">Meta: ≥110% · Clase Mundial</div>
      </div>
      <div style="background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:16px">
        <div style="font-size:10px;font-weight:700;color:var(--text3);text-transform:uppercase;letter-spacing:.6px;margin-bottom:6px">ARR Gestionado</div>
        <div style="font-size:24px;font-weight:800;color:var(--text);margin-bottom:2px">${totalARR?fmtArr(totalARR):'Sin datos'}</div>
        <div style="font-size:10px;color:var(--text3)">Revenue total bajo tu responsabilidad</div>
      </div>
      <div style="background:${arrAtRisk>0?'rgba(231,76,60,.08)':'var(--surface)'};border:1px solid ${arrAtRisk>0?'rgba(231,76,60,.3)':'var(--border)'};border-radius:12px;padding:16px">
        <div style="font-size:10px;font-weight:700;color:var(--text3);text-transform:uppercase;letter-spacing:.6px;margin-bottom:6px">Revenue en Riesgo</div>
        <div style="font-size:24px;font-weight:800;color:${arrAtRisk>0?'var(--red)':'var(--green)'};margin-bottom:2px">${arrAtRisk?fmtArr(arrAtRisk):'$0'}</div>
        <div style="font-size:10px;color:var(--text3)">${atRiskClients.length} cuentas con health 🟠/🔴</div>
      </div>
      <div style="background:rgba(46,204,113,.08);border:1px solid rgba(46,204,113,.25);border-radius:12px;padding:16px">
        <div style="font-size:10px;font-weight:700;color:var(--text3);text-transform:uppercase;letter-spacing:.6px;margin-bottom:6px">Pipeline Expansión</div>
        <div id="pipeline-total" style="font-size:24px;font-weight:800;color:var(--green);margin-bottom:2px">${pipelineTotal?fmtArr(pipelineTotal*12):'Completar tracker'}</div>
        <div style="font-size:10px;color:var(--text3)">ARR adicional posible (ingresalo ↓)</div>
      </div>
    </div>

    <!-- PRIORIDADES ESTRATÉGICAS -->
    <div style="margin-bottom:24px">
      <div style="font-size:11px;font-weight:800;color:var(--text2);text-transform:uppercase;letter-spacing:.7px;margin-bottom:12px">⚡ Mis 3 Prioridades Estratégicas Esta Semana</div>
      <div style="display:flex;flex-direction:column;gap:8px">${priorityItems}</div>
    </div>

    <!-- GRUPOS MULTIPLICADORES -->
    <div style="margin-bottom:24px">
      <div style="font-size:11px;font-weight:800;color:var(--text2);text-transform:uppercase;letter-spacing:.7px;margin-bottom:12px">🔗 Grupos Estratégicos — Una reunión, múltiples cuentas</div>
      <div style="display:flex;gap:12px;flex-wrap:wrap">${groupCards}</div>
    </div>

    <!-- CLASS A TRACKER -->
    <div style="margin-bottom:24px">
      <div style="display:flex;align-items:center;gap:10px;margin-bottom:14px">
        <div style="font-size:11px;font-weight:800;color:var(--text2);text-transform:uppercase;letter-spacing:.7px">💎 Cuentas Clase A — Strategic Tracker (${CLASS_A.length})</div>
        <div style="flex:1;height:1px;background:var(--border)"></div>
        <div style="font-size:10px;color:var(--text3)">Editá cada campo → se guarda automáticamente</div>
      </div>
      <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:14px">${classACards}</div>
    </div>

    <!-- EXPANSION PIPELINE TABLE -->
    ${pipelineRows ? `
    <div style="background:var(--surface);border:1px solid var(--border);border-radius:12px;overflow:hidden;margin-bottom:24px">
      <div style="padding:14px 18px;border-bottom:1px solid var(--border);font-size:11px;font-weight:800;color:var(--text2);text-transform:uppercase;letter-spacing:.7px">
        💰 Pipeline de Expansión — Revenue adicional identificado
      </div>
      <table style="width:100%">
        <thead><tr><th>Cliente</th><th>Tipo de expansión</th><th>ARR estimado</th><th>Próxima acción</th></tr></thead>
        <tbody>${pipelineRows}</tbody>
      </table>
    </div>` : `
    <div style="background:var(--surface);border:1px dashed var(--border);border-radius:12px;padding:24px;text-align:center;margin-bottom:24px">
      <div style="font-size:14px;color:var(--text3);margin-bottom:6px">💡 Tu pipeline de expansión aparece aquí</div>
      <div style="font-size:12px;color:var(--text3)">Completá "Oportunidad de Expansión" y "MRR adicional estimado" en las tarjetas Clase A de arriba</div>
    </div>`}

    <!-- CLASS B QUICK VIEW -->
    <div>
      <div style="font-size:11px;font-weight:800;color:var(--text2);text-transform:uppercase;letter-spacing:.7px;margin-bottom:10px">🥈 Cuentas Clase B — Monitoreo activo (${CLASS_B.length})</div>
      <div style="display:flex;flex-wrap:wrap;gap:8px">
        ${CLASS_B.map(id=>{
          const port=getPortData(id);
          const cdata=getClientData(id);
          const hs=calcHS(cdata);
          const col=hs.cl==='green'?'var(--green)':hs.cl==='yellow'?'var(--yellow)':hs.cl==='orange'?'var(--orange)':'var(--red)';
          return `<div onclick="currentClient='${id}';nav('ficha',document.getElementById('nav-ficha'))" style="cursor:pointer;background:var(--surface2);border:1px solid var(--border);border-radius:8px;padding:8px 12px;font-size:11px">
            <span style="font-weight:600">${port.name||id}</span>
            ${hs.score!=null?`<span style="color:${col};font-weight:700;margin-left:6px">${hs.score}</span>`:''}
          </div>`;
        }).join('')}
      </div>
    </div>

  </div>`;

  // Expose saveSD_ globally for inline event handlers
  window.saveSD_ = saveSD;
}

// No top-level window-attach for renderPortfolioA itself: it is only ever invoked as
// an ES-module import from src/ui/nav.js (no inline onclick/onchange references it
// directly anywhere in index.html — verified via full-file grep), matching the
// convention used by sibling files such as src/ui/catalogo.js and
// src/ui/metricas.js. `saveSD_` IS attached to `window`, but that assignment lives
// inside the function body itself (see comment above) and is preserved there
// verbatim rather than hoisted out.
export { renderPortfolioA };
